version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: g_idatt2106_a
      MYSQL_USER: g_idatt2106_a
      MYSQL_PASSWORD: GGusexLh
    ports:
      - "3307:3306"
