image: node:16.15.0-alpine

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

vue-build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd frontend
    - npm install
  artifacts:
      paths:
      - frontend/node_modules # Available in later stages

mvn-test:
  stage: test
  script:
    - cd backend
    - apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    - apk add maven
    - mvn test
vue-test:
    stage: test
    script:
      - cd frontend
      - npm run test:unit
