image: node:16.14.0-alpine

stages:
  - install
  - build
  - test
  - deploy

vue-install:
  stage: install
  script:
    - cd frontend
    - npm install
  artifacts:
      paths:
      - frontend/node_modules # Available in later stages, needed for testin, build, etc.

mvn-test:
  stage: test
  script:
    - cd backend
    - apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community # Install java 11
    - apk add maven # Install maven
    - mvn test # Run tests

vue-test:
    stage: test
    script:
      - cd frontend
      - npm run test:unit
